// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrngwrqfbwfteqzmvppo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZybmd3cnFmYndmdGVxem12cHBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MDYwOTgsImV4cCI6MjA2MTI4MjA5OH0.fAeUjUpjaQwIxjBN-SDFOpOZ0FNqW25j9a5HqF018W4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json'
    }
  }
});
